plugins:

  fortinet:
    executor: central_deployment_agent
    package_name: cloudify-fortigate-plugin
    source: cloudify-fortigate-plugin
    package_version: '0.0.0.2'

node_types:


### define a type dervied from openstack to extend the type for fortigate purpose.

  cloudify.openstack.nodes.Fortigate:
    derived_from: cloudify.openstack.nodes.Server
    properties:
      username:
        description: >
          fortigate username
        default: ""
      password:
        description: >
          fortigate password
        default: ""
      use_ssl:
        description: >
          http or https
        type: boolean
        default: false
      verify_ssl:
        description: >
          A boolean which controls whether we verify
          the server's TLS certificate.
        type: boolean
        default: true
      vdom:
        description: >
          vdom of the fortigate to use, can use global here if necessary
        type: string
        default: "root"

    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: fortinet.fortigate_plugin.tasks.execute
          inputs:
            params:
              default:
                fgt_password: { get_property: [SELF, password]}
                fgt_ip: { get_attribute: [SELF, ip]}
                fgt_user: { get_property: [SELF, username]}
                fgt_name: { get_attribute: [SELF, server, name ] }
            template_file:
              default: templates/license_check.yaml
